# permissions for end users to edit restapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: restapi-editor-role
rules:
- apiGroups:
  - restapi.example.com
  resources:
  - restapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - restapi.example.com
  resources:
  - restapis/status
  verbs:
  - get
