---
- name: start Restapi
  community.kubernetes.k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-restapi'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        replicas: "{{ size }}"
        selector:
          matchLabels:
            app: restapi
        template:
          metadata:
            labels:
              app: restapi
          spec:
            containers:
            - name: restapi
              image: "docker.io/imjoseangel/restapi:latest"
              ports:
                - containerPort: 5000
