---
- name: start Restapi
  community.kubernetes.k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-restapi'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        replicas: "{{ size }}"
        selector:
          matchLabels:
            app: restapi
        template:
          metadata:
            labels:
              app: restapi
          spec:
            containers:
            - name: restapi
              image: "docker.io/imjoseangel/restapi:latest"
              imagePullPolicy: Always
              ports:
                - containerPort: 5000
              resources:
                requests: # minimum resources required
                  cpu: 250m
                  memory: 64Mi
                limits: # maximum resources allocated
                  cpu: 500m
                  memory: 256Mi
              readinessProbe: # is the container ready to receive traffic?
                httpGet:
                  port: 5000
                  path: /
              livenessProbe: # is the container healthy?
                httpGet:
                  port: 5000
                  path: /
